DROP TABLE IF EXISTS `menu`;
CREATE TABLE `menu` (
  `entry` INT UNSIGNED NOT NULL,
  `menu` INT UNSIGNED DEFAULT NULL,
  `func` INT UNSIGNED DEFAULT NULL,
  `mask` INT UNSIGNED DEFAULT NULL,
  `level` INT UNSIGNED DEFAULT NULL,
  `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `param1` FLOAT DEFAULT NULL,
  `param2` FLOAT DEFAULT NULL,
  `param3` FLOAT DEFAULT NULL,
  `param4` FLOAT DEFAULT NULL,
  `param5` FLOAT DEFAULT NULL,
  `price` INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`entry`)
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_general_ci 
  ROW_FORMAT=Dynamic;

